server:
  - name: "api"
    addr: ":8080"
    middlewares: []
    routergroups:
      - group: "/admin"
        middlewares: []
        routers:
          - path: "/abc"
            methods: ["GET"]
            handlers: ["main.Login?Times=10"]